name: GitHub Pages
on:
  push:
    branches: [master]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --tags || true
      - uses: cachix/install-nix-action@v6

      - name: build
        run: nix-build -A site

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./result
